### ISSUE TITLE
Async shutdown for IO

### ISSUE THREAD

**Issue by seanmonstar** [alexcrichton/tokio-io#11]
Some things would previously have implemented `Io` have need to perform read/write ops before closing the socket. An example is `TlsStream`, such as provided by tokio-tls. For higher level abstractions, like making a `Transport` over `Io` (now `AsyncRead + AsyncWrite`), the knowledge of if a shutdown is necessary isn't available. This probably should be implemented on the stream (`TlsStream`), on a trait, and the wrapping `Transport` should have some trait method to call.

This could have a default implementation of just returning `futures::ok()`, and then specific streams can implement how they need. I can't easily say if it should be on `AsyncWrite`, since something may require both reading and writing in order to communicate a clean shutdown.

**Comment by carllerche** [comment]
I think the answer is to add a fn to `AsyncWrite` that includes a default impl (similar to flush).

Maybe something like:

```
trait AsyncWrite: io::Write {
    // other fns

    fn start_close(&mut self) -> io::Result<()> {
        Ok(())
    }
}
```

The expectation being that one should always call `start_close` before dropping an I/O handle, then call `flush()` until it returns `Ok(())`. Only then would it be safe to drop the handle.

Transports, on the other hand, can handle the shutdown case by receiving `Option<T>` as the inbound message type, using `None` to signal a shutdown.

**Comment by alexcrichton** [comment]
This seems like a reasonable feature to have, and I think adding it to the trait is right. Perhaps something like this though?

```rust
fn poll_close(&mut self) -> Poll<(), io::Error>;
```

That way it's similar to `Sink::poll_complete` where it can imply that I/O is done in the background and otherwise `Ok(())` means that the close operation is completed. In general we could then document that using an I/O stream after `poll_close` has succeeded is not guaranteed to work, and may panic.

**Comment by alexcrichton** [comment]
I've opened https://github.com/alexcrichton/tokio-io/pull/15 as an avenue here.
