### ISSUE TITLE
Consider switching Framed & co. to be generic over the error vs. using io::Error

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/tokio-io#12]
This has been requested a few times. I am creating this issue to track the discussion.

The original point for adding `Codec` in tokio-core was to provide an **easy** path to get from a TCP -> a server using tokio-proto. In the server case, tokio-proto is the on handling the socket. As such, it is unable to take advantage of "generic" errors. If the codec errors out, tokio-proto shutdown the connection. Given that the goal is an **easy mode** to plug into tokio-proto, and that -proto requires an io::Error (or some fixed error type) anyway, Codec was hard coded to io::Error in order to remove that decision for a newcomer to Tokio.

A number of requests have been made to switch `Encoder` / `Decoder` (the next iteration of `Codec`) to be generic over error. This would depart from the original goal described above to make it a more general purpose abstraction for building transports.

The questions as far as I can tell are:

a) How much does this change impact the getting started experience?
b) Should the getting started experience be split out from `Framed`?

**Comment by Ralith** [comment]
If the goal is purely to support tokio-proto, rather than to be a more broadly useful abstraction, shouldn't such an abstraction be part of tokio-proto rather than tokio-core? For that matter, if all tokio-proto does is shut down the connection on error, why does it need to make any assumptions about the error type at all? If the information's going to be thrown away anyway, any `Decoder` could easily be wrapped to produce a `Decoder<Error=()>`, or such a type could be required at the interface.

Bearing in mind a goal to be accessible, I strongly feel that encouraging new developers to overload `io::Error` to represent errors other than those raised by the OS is not a good idea. Even a `Result<T, ()>` return type would be preferable to that, particularly if the information's to be discarded anyway. However, in my own code, this information is *not* thrown away, and from discussion on gitter and in https://github.com/tokio-rs/tokio-core/issues/146 I gather that I'm not alone in this--it's difficult to debug a codec if errors result in silent death, after all.

It would be unfortunate for tokio-core to optimize its public interface for the needs of a single downstream library when many users have different requirements, forcing people to write bad code and/or duplicate effort. Placing the general solution in a third-party external crate is possible, but establishes a very strange precedent, and will inevitably lead to people awkwardly wedging their code into the special-cased interface just because it's more readily available.

If a downstream library wants to provide a simplified experience, there's nothing wrong with that, but I think the core library should focus on providing foundational, idiomatic and broadly reusable tools. These absolutely don't need to be the exact tools that a tokio-proto, tokio-service, or other high-level library user is presented with. If a developer is seeking to work directly with the abstractions provided by the lowest level component available, their needs are likely to be different than those of one working with the highest.

**Comment by carllerche** [comment]
From another thread:

> After talking it over, I think we can move forward w/ generic errors, but with a From<io::Error> bound. This reduces the number of types & complexity exposed in the public API. The BytesRemaining error could always be introduced in user code by implementing decode_eof.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/tokio-io/pull/10
